adding results for temp CI checker

diff --git a/.github/workflows/basic_gh_workflow.yml b/.github/workflows/basic_gh_workflow.yml
--- a/.github/workflows/basic_gh_workflow.yml
+++ b/.github/workflows/basic_gh_workflow.yml
@@ -27,10 +27,7 @@ jobs:
 
       # Runs a single command using the runners shell
       - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+        run: cmp -s result.json ok_result.json || echo "::error not all requirements met, cannot merge"
+          
+      # later
+      #cmp -s $(curl -s --header "Content-Type: application/json"  --request GET  --data '{"projectId":"1"}'  http://localhost:3000/api/allApproved) ok_result.json || echo "the results are different"
